### ISSUE TITLE
Plots enhancement

### ISSUE THREAD

**Issue by sbridel** [tuxette/SOMbrero#1]
Your package is very interesting.

You can find an awesome R code which plot U-Matrix and Components plots in nice hexagonal plots for SOM

https://github.com/geoss/som_visualization_r

This project seems not to be developed  anymore.
So it will be sad if we lose this work

**Comment by tuxette** [comment]
Thanks for the tip: I'll try to find the time to do that. That would indeed be interesting.

**Comment by tuxette** [comment]
hexagonal plots are implemented in version 1.4 of SOMbrero
