### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by alexsomoza** [tuxette/SOMbrero#3]
What means this error ????

Error in (1 - epsilon * the.nei) * prototypes : arreglos de dimensón no compatibles

and how can I fix it ????

Thanks a lot.

**Comment by tuxette** [comment]
It's probably a bug coming from a special case that we have not encountered before. Can you provide a reproducible example and we will fix it.

**Comment by tuxette** [comment]
to be confirmed but probably fixed in version 1.4-1 of SOMbrero
